### ISSUE TITLE
Update icon when re-loading Jira List

### ISSUE THREAD

**Issue by jkuester** [roblangenfeld/JIRA-Quick-Link-Extension#4]
When updating the selected tags in the options, the list of jiras for the user is reloaded.  However, there is no visual indicator to the user that this is happening and the reload can take several seconds. 

Would be nice to update the icon somehow to show that it is refreshing the number. Then set it to the new number when the refresh completes.

**Comment by TobiTenno** [comment]
Dupe, see #2 
It refreshes in the background right now, intentionally not when the user clicks it.
